### ISSUE TITLE
Cannot find 'model_scope_diffusers'

### ISSUE THREAD

**Issue by hynnsk** [buxiangzhiren/VD-IT#4]
Hi,
Thank you for your work

I tried to run your code, but there is an error like:

```
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './Text-To-Video-Finetuning/mymodels/model_scope_diffusers'. Use `repo_type` argument if needed.
```

It seems like there is no model_scope_diffusers in ./Text-To-Video-Finetuning/mymodels/.

It would be very kind for you to teach me where I am wrong.

Thank you.

**Comment by buxiangzhiren** [comment]
Can you try "git clone https://huggingface.co/damo-vilab/text-to-video-ms-1.7b" directly?

**Comment by buxiangzhiren** [comment]
Then move all downloaded files to this direction "./mymodels/model_scope_diffusers/"

**Comment by hynnsk** [comment]
Thank you for your quick response.
I just checked that there's a guide on Readme,

Thank you
